### ISSUE TITLE
Improve the checkout page

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/llorix-one-lite#192]
We can make some small improvements to the checkout page. This is how it looks now https://prnt.sc/iqltrk
move the Your order box to the right, the coupon code lower like we have in the other themes. You can have a look at Zerif for example https://github.com/Codeinwp/zerif-lite/commit/fe0021cd86b6d155c0d6332db169c8923a8448ba .
Align the checkboxes https://prnt.sc/iqm52e

Plus, on single product page, maybe fix the alignment issue for the gallery https://prnt.sc/iqlqi5

**Comment by rodica-andronache** [comment]
@cosmin-serbanescu looking good 💃 maybe would be nice to also style the Apply coupon button to match the Place order button? And have the same font size for all texts ? Some notices are bigger, some smaller https://prnt.sc/irk0u3

**Comment by cosmin-serbanescu** [comment]
@rodica-andronache , had to make them all 16px as the buttons weren't looking good at 12px while the general font size was 16 + found & fixed an issue on the variable products also on checkout.

**Comment by rodica-andronache** [comment]
@cosmin-serbanescu I'm not sure about this buttons on the checkout page https://prnt.sc/is2swi :D and even on the cart page https://prnt.sc/is2t7o. We should have them all consistent across the theme. This is the normal button style in the theme https://prnt.sc/is2tju . Would it be possible to have it the same everywhere?
And for the notices, could we have the same font size as the rest of the page https://prnt.sc/is2uld ? Right now, those areas stand up more than the actual fields on the checkout page. You can have a look at Hestia https://demo.themeisle.com/hestia-pro/checkout/

**Comment by cosmin-serbanescu** [comment]
fixed checkout & cart page: buttons, fonts, terms and conditions positioning, coupon fields adjustments

**Comment by rodica-andronache** [comment]
thanks!
some small responsive problems still: the apply coupon button https://prnt.sc/iu9rzf on the cart page and on checkout https://prnt.sc/iu9shb , login form on checkout https://prnt.sc/iu9tbn , paypal on checkout https://prnt.sc/iu9s92

**Comment by cosmin-serbanescu** [comment]
fixed them! take a look and let me know!
